version: "2"
run:
  timeout: 5m
linters:
  default: all
  settings:
    cyclop:
      max-complexity: 12
    funlen:
      lines: -1
      statements: 50
  disable:
    - forbidigo
    - ireturn
    - contextcheck
    - err113
    - exhaustive
    - tagliatelle
    - fatcontext
    - noctx
    - mnd
    - musttag
    - revive
    - gosmopolitan
    - varnamelen
    - wrapcheck
    - gochecknoglobals
    - exhaustruct
    - depguard
    - nlreturn
    - wsl
  exclusions:
    generated: lax
    warn-unused: true
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
