version: "2"
linters:
  default: all
  settings:
    cyclop:
      max-complexity: 12
    funlen:
      lines: -1
      statements: 51
  disable:
    - ireturn
    - contextcheck
    - err113
    - godot
    - exhaustive
    - tagliatelle
    - fatcontext
    - noctx
    - mnd
    - musttag
    - revive
    - gosmopolitan
    - varnamelen
    - wrapcheck
    - gochecknoglobals
    - exhaustruct
    - depguard
    - nlreturn
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
