version: "2"
run:
  timeout: 5m
linters:
  default: all
  settings:
    cyclop:
      max-complexity: 12
    funlen:
      lines: -1
      statements: 50
    exhaustive:
      default-signifies-exhaustive: true
    gosmopolitan:
      allow-time-local: true
    varnamelen:
      max-distance: 10
      ignore-decls:
        - wg *sync.WaitGroup
        - w http.ResponseWriter
        - r *http.Request
        - tx *bbolt.Tx
        - db *bbolt.DB
        - ok int
  disable:
    - musttag
    - ireturn
    - err113
    - tagliatelle
    - mnd
    - wrapcheck
    - gochecknoglobals
    - exhaustruct
    - depguard
    - noinlineerr
    - nlreturn
    - wsl
    - wsl_v5
  exclusions:
    generated: lax
    warn-unused: true
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
